// Woordenlijst Les 1 + Les 5 (thema: theater & film)
const WORDS = [
  // Les 1
  { woord: "de acteur", omschrijving: "Iemand die een rol heeft in een film of in een toneelstuk.", les: 1 },
  { woord: "de auditie", omschrijving: "Een proefoptreden. Je zingt, speelt of danst om te laten zien wat je kunt.", les: 1 },
  { woord: "de auteur", omschrijving: "De schrijver.", les: 1 },
  { woord: "de componist", omschrijving: "Iemand die muziekstukken bedenkt en ze opschrijft met muzieknoten.", les: 1 },
  { woord: "het decor", omschrijving: "Alle voorwerpen die op het podium staan tijdens een toneelstuk. Je kunt eraan zien waar de voorstelling zich afspeelt.", les: 1 },
  { woord: "dolgelukkig", omschrijving: "Heel gelukkig.", les: 1 },
  { woord: "de geluidsman", omschrijving: "Iemand die er bij een voorstelling zorgt dat alle geluiden en stemmen goed te horen zijn.", les: 1 },
  { woord: "de hoofdrol", omschrijving: "De belangrijkste rol bij een film of een toneelstuk.", les: 1 },
  { woord: "kleurrijk", omschrijving: "Met veel verschillende kleuren.", les: 1 },
  { woord: "langdradig", omschrijving: "Saai.", les: 1 },
  { woord: "ontroerend", omschrijving: "Als iets je een mooi en verdrietig gevoel geeft. Het raakt je gevoel.", les: 1 },
  { woord: "de ontwerper", omschrijving: "Iemand die bedenkt en tekent hoe iets eruit moet gaan zien.", les: 1 },
  { woord: "de ovatie", omschrijving: "Een groot applaus.", les: 1 },
  { woord: "de plankenkoorts", omschrijving: "Een zenuwachtige angst voor een optreden.", les: 1 },
  { woord: "het podium", omschrijving: "Verhoging waarop een optreden plaatsvindt.", les: 1 },
  { woord: "de première", omschrijving: "De eerste voorstelling.", les: 1 },
  { woord: "de regisseur", omschrijving: "Iemand die de leiding heeft over de uitvoering van een toneelstuk of een film.", les: 1 },
  { woord: "het rekwisiet", omschrijving: "Een voorwerp dat gebruikt wordt in een voorstelling.", les: 1 },
  { woord: "repeteren", omschrijving: "Oefenen voor een voorstelling of toneelstuk.", les: 1 },
  { woord: "de theatervoorstelling", omschrijving: "Een voorstelling in een theater. Bijvoorbeeld een toneelstuk.", les: 1 },

  // Les 5
  { woord: "aanraden", omschrijving: "Iemand de raad geven iets wel te doen.", les: 5 },
  { woord: "afraden", omschrijving: "Iemand de raad geven iets niet te doen.", les: 5 },
  { woord: "het geluidseffect", omschrijving: "Een bijzonder geluid dat te horen is in een voorstelling.", les: 5 },
  { woord: "de kritiek", omschrijving: "Zeggen wat er niet goed is aan wat iemand doet.", les: 5 },
  { woord: "lovend", omschrijving: "Aanprijzend, met complimenten.", les: 5 },
  { woord: "negatief", omschrijving: "Gezegd van iemand die afkeurende kritiek heeft.", les: 5 },
  { woord: "noteren", omschrijving: "Opschrijven, aantekenen.", les: 5 },
  { woord: "de pers", omschrijving: "De journalisten en de krant, radio of de televisie waar ze voor schrijven.", les: 5 },
  { woord: "het personage", omschrijving: "Een persoon die in een boek, toneelstuk of film voorkomt.", les: 5 },
  { woord: "het plot", omschrijving: "Het verloop van een verhaal van het begin tot het einde.", les: 5 },
  { woord: "positief", omschrijving: "Gezegd van iemand die opbouwende kritiek heeft.", les: 5 },
  { woord: "de recensie", omschrijving: "Een mening over een boek, toneelstuk of film. Het is meestal geschreven in een krant of tijdschrift.", les: 5 },
  { woord: "de recensent", omschrijving: "Iemand die voor een krant of tijdschrift schrijft wat hij van een voorstelling, boek of film vindt.", les: 5 },
  { woord: "de repetitie", omschrijving: "De keer dat je een muziekstuk of voorstelling oefent.", les: 5 },
  { woord: "de roem", omschrijving: "Grote bekendheid, bewonderd worden door heel veel mensen.", les: 5 },
  { woord: "het scenario", omschrijving: "Een beschrijving van de delen van een film of een toneelstuk.", les: 5 },
  { woord: "de scène", omschrijving: "Een deel van een film of een toneelstuk.", les: 5 },
  { woord: "het theatergezelschap", omschrijving: "Een groep mensen die samen een toneelstuk speelt.", les: 5 },
  { woord: "voorspelbaar", omschrijving: "Als je weet wat er gaat komen, is iets voorspelbaar.", les: 5 },
  { woord: "de waardering", omschrijving: "Hoe belangrijk en waardevol je iets vindt.", les: 5 },
];
